# Generated by Django 3.1.3 on 2020-11-25 15:49

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201125_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=profiles.models.user_directory_path, verbose_name='pictures'),
        ),
    ]
